package me.doublenico.scaraGUI.button;

public enum ButtonType {
    DELETE_BUTTON,
    LOAD_APP,
    MODIFY_BUTTON,
    CHOOSE_BUTTON,
    SAVE_BUTTON,
    SETTINGS_BUTTON,
    CREATE_NEW_APP_BUTTON,
    REFRESH_BUTTON,
    CONNECT_BUTTON,
    DISCONNECT_BUTTON,
    BACK_BUTTON,
    MOVE_UP_BUTTON,
    MOVE_DOWN_BUTTON,
    ADD_BUTTON,
    CLOSE_BUTTON,
    SIDEBAR_BUTTON,
    PRESET_BUTTON,
    DIRECTIONAL_BUTTON,
    HOME_BUTTON,
    MOTOR_TEST_BUTTON,
    LOG_VIEWER_BUTTON,
    RUN_BUTTON;
}
